### ISSUE TITLE
Adjust title to Homefront Supporter Series, add detail

### ISSUE THREAD

**Issue by curieuxqueen** [nyxl-venoms/homefront.5dv.nyc#14]
Change browser title and the text to refer to Homefront Supporter Series. 
Additionally, below in a smaller font, include this text:

December 22, 2019 | 1PM - 7PM ET | Live at http://twitch.tv/nyxl

**Comment by curieuxqueen** [comment]
https://media.discordapp.net/attachments/408265407523323918/655997952816316416/unknown.png

**Comment by buzzedword** [comment]
![image](https://user-images.githubusercontent.com/334485/70880760-2eddcf80-1f98-11ea-95fd-2a61c79f51fb.png)
copy for the lazy

**Comment by UnnDunn** [comment]
This is resolved with pull request #25
