### ISSUE TITLE
ATL - Add Copy

### ISSUE THREAD

**Issue by buzzedword** [nyxl-venoms/homefront.5dv.nyc#42]
> Atlanta Royal Family was founded as a way for all the fans and content creators of Atlanta Reign to come together and be more than a sum of their parts. Watch parties, casual meetups, local community volunteer work, there's never a time you can't come out and join other Reign fans. From 3 people to now over 300, The Royal Family has grown to be a cornerstone in the Atlanta community, covering not only Overwatch and Call of Duty, but volunteer initiatives in the surrounding areas as well. 

LOGO

> Atlanta Royal Family is proud to partner with Children's Healthcare of Atlanta, where doctors, nurses and staff are specially trained to care for children under the age of 21. From colorful, friendly waiting rooms to equipment that fits patients of all sizes, every detail is designed specifically for kids. For over 100 years they've been 100 percent dedicated to kids. From their focus on family support and treating the whole child, to their specialized equipment and techniques, they are tireless in our pursuit of providing the best possible care for children, and we are proud to help with that goal.

**Comment by buzzedword** [comment]
Copy needs to be double checked on 12/17/2019

**Comment by curieuxqueen** [comment]
Update to below:

Atlanta Royal Family was founded to bring all the fans and content creators of Atlanta Reign together to be more than the sum of their parts. At anytime, you can join other Reign fans for watch parties, casual meetups, community volunteer work, and more. From 3 people to over 300, the Atlanta Royal Family grew to be a cornerstone in the community covering Overwatch, Call of Duty, and volunteer initiatives across Atlanta.

-

Atlanta Royal Family is proud to partner with Children's Healthcare of Atlanta, where the staff is specially trained to care for all children. For over 100 years, they have been completely dedicated to children. With a focus on supporting families, specialized equipment, and refined techniques, they tirelessly pursue providing the best possible care, and we are proud to help with this goal.
