### ISSUE TITLE
LSV - Add Copy

### ISSUE THREAD

**Issue by buzzedword** [nyxl-venoms/homefront.5dv.nyc#43]
TBD

**Comment by curieuxqueen** [comment]
"Howdy,
We are the Lone Star Vanguard, a group of individuals across Texas sharing a common goal; to celebrate our love for nerd culture and embolden future generations through positivity! What started as five friends sitting down to view the inaugural season of The Overwatch League to root on the Houston Outlaws, now has active members in NY, AR, KY, CA, and TX, the LSV has become a community that welcomes all who are looking to find a friend with an open mind.

As we strive toward our objective, the community is giving back by fighting for kids! We thrilled to partner with Dell Children's Hospital for a second straight year to benefit Children in need of special medical attention through the love of video games."
