### ISSUE TITLE
Global - Add links to teams

### ISSUE THREAD

**Issue by buzzedword** [nyxl-venoms/homefront.5dv.nyc#58]
5DV: https://twitter.com/nyxl_venoms
TAF: https://twitter.com/alphaflight_TO
LSV: https://twitter.com/LSVanguard
ATL: https://twitter.com/ATLRoyalFamily

## Requirements
- Links open in new tab
- No unnecessary active/hover effects
- Unstyled
- Does not impede screen readers

**Comment by UnnDunn** [comment]
Where should these links go? In the copy for each supporter's group? In a separate call-out block?

**Comment by buzzedword** [comment]
@curieuxqueen had originally suggested that these are the logos directly, similarly to how we have the partners in the footer set up.

**Comment by UnnDunn** [comment]
I'm going to add the links to the logos at the top of each column. I feel like that makes sense. 🤷🏽‍♂️
