### ISSUE TITLE
Footer - Sponsor block needs to be constrained to the same width as the team block

### ISSUE THREAD

**Issue by buzzedword** [nyxl-venoms/homefront.5dv.nyc#6]
![image](https://user-images.githubusercontent.com/334485/70871916-d98ec780-1f71-11ea-98c7-48fa685c8bc3.png)

Currently lorem ipsum text demonstrates sponsor text extending beyond the bounds of the team block. This needs to constrain to the same grid that the team block is in (`.pricingTiers .tiers`)

**Comment by UnnDunn** [comment]
I'll style it properly once we know what's going in there.

**Comment by curieuxqueen** [comment]
lets make it centered too!
