### ISSUE TITLE
Global - Crew columns background and text color

### ISSUE THREAD

**Issue by buzzedword** [nyxl-venoms/homefront.5dv.nyc#62]
@curieuxqueen: "ok, need a darker grey text and can we make the white column opacity 80%?
change the columns to E0DEDE and text to 4D4D4D"

![image](https://user-images.githubusercontent.com/334485/70971836-cf52f300-206f-11ea-8d33-eab099a62714.png)

**Comment by UnnDunn** [comment]
Changed the colors. Let's leave this issue open until we have colors we're happy with.
