### ISSUE TITLE
Open Graph tags need to be populated for social shares

### ISSUE THREAD

**Issue by buzzedword** [nyxl-venoms/homefront.5dv.nyc#80]
Requires: 
- Title under 72 characters
- Description under 124 characters
- Image to use for site preview

Twitter specific: what account to credit with @mention

This will be used on Facebook, Twitter, and start populating Google Search results.

**Comment by buzzedword** [comment]
![image](https://user-images.githubusercontent.com/334485/71041702-b68e2000-20f7-11ea-9abe-c37eaae7bc8c.png)

Proposed card preview image

**Comment by curieuxqueen** [comment]
- Title under 72 characters: Homefront Supporter Series | December 22, 2019 
- Description under 124 characters: The Homefront Supporter Series rallies OWL supporters crews to support city-based charities and help at-need neighbors. 

Twitter account to tag: @nyxl_venoms (yolo)
